In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
from pandas import Series ,DataFrame

In [3]:
arr =np.arange(9).reshape((3,3))

In [4]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr,arr],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [17]:
ser1 =Series([0,1,2],index=["T","U","V"])
ser2 =Series([3,4,5],index=["X","Y","U"])

In [8]:
ser1


T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [14]:
pd.concat([ser1,ser2],axis=0)

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [18]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  5.0
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [19]:
pd.concat([ser1,ser2],axis=1,keys=["jon","oka"])

jon  oka
T  0.0  NaN
U  1.0  5.0
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [26]:
dframe1 = DataFrame(np.random.randn(4,3),columns=["X","Y","Z"])

In [27]:
dframe1

X         Y         Z
0 -0.305108 -0.021769  0.385367
1 -0.009617  0.586256  1.079908
2  0.223799  0.543268  0.803846
3  2.197731  0.756919  0.254243

In [28]:
dframe2 = DataFrame(np.random.randn(3,3),columns=["Q","Y","X"])

In [29]:
dframe2

Q         Y         X
0 -0.700188  1.732431  1.566640
1  1.023840 -0.975213 -0.733326
2  0.725269 -0.808192  0.990427

In [31]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -0.305108 -0.021769  0.385367       NaN
1 -0.009617  0.586256  1.079908       NaN
2  0.223799  0.543268  0.803846       NaN
3  2.197731  0.756919  0.254243       NaN
0  1.566640  1.732431       NaN -0.700188
1 -0.733326 -0.975213       NaN  1.023840
2  0.990427 -0.808192       NaN  0.725269

In [32]:
pd.concat([dframe1,dframe2],ignore_index=True)## ,ignore_index 新しく左側を作り直す

X         Y         Z         Q
0 -0.305108 -0.021769  0.385367       NaN
1 -0.009617  0.586256  1.079908       NaN
2  0.223799  0.543268  0.803846       NaN
3  2.197731  0.756919  0.254243       NaN
4  1.566640  1.732431       NaN -0.700188
5 -0.733326 -0.975213       NaN  1.023840
6  0.990427 -0.808192       NaN  0.725269

In [33]:
ser =Series([2,np.nan,3,np.nan,6,np.nan],index=["Q","R","S","T","U","V"])

In [34]:
ser

Q    2.0
R    NaN
S    3.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [35]:
ser2 =Series(np.arange(len(ser),dtype=np.float64) ,index=["Q","R","S","T","U","V"])

In [36]:
# Series(np.)
np.where(pd.isnull(ser))#seriesからnulのとこから数字番号を持ってくる

(array([1, 3, 5]),)

In [40]:
Series(np.where(pd.isnull(ser),ser2,ser),index=ser.index)
# ser.combine_first(ser2)と同じ意味

Q    2.0
R    1.0
S    3.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [41]:
ser.combine_first(ser2)

Q    2.0
R    1.0
S    3.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [42]:
dframe_odds = DataFrame({'X': [1., np.nan, 3., np.nan],
                     'Y': [np.nan, 5., np.nan, 7.],
                     'Z': [np.nan, 9., np.nan, 11.]})
dframe_evens = DataFrame({'X': [2., 4., np.nan, 6., 8.],
                     'Y': [np.nan, 10., 12., 14., 16.]})

In [43]:
dframe_odds



X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [44]:
dframe_evens

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [45]:
dframe_odds.combine_first(dframe_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

In [50]:
dframe =DataFrame(np.arange(8).reshape((2,4)), index=pd.Index(["LA","SP"],name="city"), columns=pd.Index(["A","B","C","D"],name="letter"))

In [51]:
dframe

letter  A  B  C  D
city              
LA      0  1  2  3
SP      4  5  6  7

In [53]:
dframe_st =dframe.stack()

In [54]:
dframe_st.unstack()

letter  A  B  C  D
city              
LA      0  1  2  3
SP      4  5  6  7

In [57]:
dframe_st.unstack(2)

IndexError: Too many levels: Index has only 2 levels, not 3

In [58]:
# NaNの扱い
ser1 = Series([0, 1, 2], index=['Q', 'X', 'Y'])
ser2 = Series([4, 5, 6], index=['X', 'Y', 'Z'])

In [59]:
dframe =pd.concat((ser1,ser2),keys=["å","B"])

In [60]:
dframe

å  Q    0
   X    1
   Y    2
B  X    4
   Y    5
   Z    6
dtype: int64

In [61]:
ser1

Q    0
X    1
Y    2
dtype: int64

In [63]:
ser2

X    4
Y    5
Z    6
dtype: int64

In [65]:
dframe.unstack(1)

Q    X    Y    Z
å  0.0  1.0  2.0  NaN
B  NaN  4.0  5.0  6.0

In [66]:
dframe.unstack(0)

å    B
Q  0.0  NaN
X  1.0  4.0
Y  2.0  5.0
Z  NaN  6.0

In [67]:
## ピポットテーブル

In [70]:
from pandas import Series, DataFrame
import pandas.util.testing as tm


In [71]:
# このセルの内容は、理解できなくても大丈夫です。
# ただサンプルになるデータを作りたいだけですので、出来たデータをどのような加工するかに注目してください。

tm.N = 3

# ちょっとした関数を作ります。
def unpivot(frame):
    N, K = frame.shape
    data = {'value' : frame.values.ravel('F'),
            'variable' : np.asarray(frame.columns).repeat(N),
            'date' : np.tile(np.asarray(frame.index), K)}
    return DataFrame(data, columns=['date', 'variable', 'value'])

# DataFrameを作ります。
dframe = unpivot(tm.makeTimeDataFrame())

In [72]:
dframe

date variable     value
0   2000-01-03        A -1.939320
1   2000-01-04        A  0.488860
2   2000-01-05        A -2.616680
3   2000-01-06        A -0.081874
4   2000-01-07        A  0.572827
..         ...      ...       ...
115 2000-02-07        D  0.167107
116 2000-02-08        D  3.635409
117 2000-02-09        D -0.970300
118 2000-02-10        D -1.552008
119 2000-02-11        D -1.014600

[120 rows x 3 columns]

In [75]:
dframe.loc[:,"variable"]

0      A
1      A
2      A
3      A
4      A
      ..
115    D
116    D
117    D
118    D
119    D
Name: variable, Length: 120, dtype: object

In [76]:
dframe.groupby("variable").mean()

value
variable          
A        -0.137192
B        -0.026881
C         0.017506
D         0.159415

In [78]:
dframe_piv = dframe.pivot('date','variable','value')
dframe_piv

variable           A         B         C         D
date                                              
2000-01-03 -1.939320  0.145590 -1.701707  1.254003
2000-01-04  0.488860 -0.288009 -1.258359  0.980246
2000-01-05 -2.616680 -0.189719 -0.886619 -0.310105
2000-01-06 -0.081874 -0.205887  2.095034  0.514029
2000-01-07  0.572827 -1.344927  0.226764 -0.198223
2000-01-10  2.595577 -0.465559  1.752121  1.251846
2000-01-11 -0.499987 -1.570251  0.910640 -0.261915
2000-01-12 -0.060995 -0.061803 -0.241983 -1.402467
2000-01-13  1.631741 -2.285418  1.546460  1.760037
2000-01-14 -0.458777  0.095166  0.407814  0.027150
2000-01-17 -0.516093 -0.362217  0.641849  0.183094
2000-01-18 -0.036474 -0.242524 -1.026555  0.407250
2000-01-19 -0.648271  0.475994 -1.458002 -0.908829
2000-01-20 -0.863311  0.671052  0.259589 -0.257591
2000-01-21  0.607079 -0.843023  1.156083 -1.688867
2000-01-24 -1.845601  0.950799  0.332740 -0.475409
2000-01-25 -0.689064 -0.867692 -0.149199  1.471008
2000-01-26  1.115877  0.281471  1.324962  0.216819
2000-01-27  0.342627  0.326065 -0.520795 -0.444392
2000-01-28  1.448376  0.990453 -0.687315  0.042573
2000-01-31 -0.414728 -1.191397  0.495695  0.608967
2000-02-01 -0.230730 -0.832810 -0.311204  0.523438
2000-02-02  0.527925  0.205272 -1.085406  2.224378
2000-02-03 -0.012178  0.495839 -0.065388 -0.730828
2000-02-04 -0.448180 -0.668237  1.053995 -0.269362
2000-02-07  1.227752  0.901702 -1.535750  0.167107
2000-02-08 -0.235275  1.537616  0.680184  3.635409
2000-02-09  0.344684  1.135816 -1.655967 -0.970300
2000-02-10 -1.981709  1.222723 -0.689240 -1.552008
2000-02-11 -1.439845  1.177480  0.914729 -1.014600

In [79]:
dframe11 =DataFrame({"keys":["A"]*2+["B"]*3,"keys1":[2,2,2,3,3]})

In [80]:
dframe11

keys  keys1
0    A      2
1    A      2
2    B      2
3    B      3
4    B      3

In [81]:
dframe11.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [83]:
pda =dframe11.drop_duplicates()

In [89]:
pda(pd.ignore_index=True)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (<ipython-input-89-b697ca60acb6>, line 1)

In [87]:
a

True

In [85]:
pda

keys  keys1
0    A      2
2    B      2
3    B      3

In [91]:
# 

In [93]:
dframe0 = DataFrame({'city':['Alma','Brian Head','Fox Park'],
                    'altitude':[3158,3000,2762]})

In [94]:
dframe0

city  altitude
0        Alma      3158
1  Brian Head      3000
2    Fox Park      2762

In [95]:
state_map={'Alma':'Colorado','Brian Head':'Utah','Fox Park':'Wyoming'}


In [96]:
state_map

{'Alma': 'Colorado', 'Brian Head': 'Utah', 'Fox Park': 'Wyoming'}

In [100]:
dframe0["state"] =dframe0["altitude"].map(state_map)
#                                      適する引数が必要


In [101]:
dframe0

city  altitude state
0        Alma      3158   NaN
1  Brian Head      3000   NaN
2    Fox Park      2762   NaN

In [102]:
ser1 = Series([1,2,3,4,1,2,3,4])



In [103]:
ser1

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [104]:
ser1.replace(1,np.nan)

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    2.0
6    3.0
7    4.0
dtype: float64

In [105]:
ser1.replace([1,2],[100,4000000])

0        100
1    4000000
2          3
3          4
4        100
5    4000000
6          3
7          4
dtype: int64

In [107]:
ser1.replace({4:np.nan})

0    1.0
1    2.0
2    3.0
3    NaN
4    1.0
5    2.0
6    3.0
7    NaN
dtype: float64

In [108]:
dframe12 =DataFrame(np.arange(12).reshape((3,4)),index=["NY","LA","SF"],columns=["A","B","C","D"])

In [109]:
dframe12

A  B   C   D
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [110]:
str.lower("A")

'a'

In [114]:
dframe12.index =dframe12.index.map(str.lower)

In [115]:
dframe12

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [116]:
str.title("udemy is good")

'Udemy Is Good'

In [117]:
dframe12.rename(index=str.title,columns=str.lower)

a  b   c   d
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [118]:
dframe12.index=np.arange(3)

In [119]:
dframe12

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [120]:
dframe12 =DataFrame(np.arange(12).reshape((3,4)),index=["NY","LA","SF"],columns=["A","B","C","D"])

In [121]:
dframe12.rename(index=str.title,columns=str.lower)

a  b   c   d
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [122]:
import pandas as pd
years =[1990,1991,1992,2008,2012,2015,1987,1969,2013,2008,1999]

In [123]:
len(years)

11

In [124]:
decade_bins = [1960,1970,1980,1990,2000,2010,2020]


In [126]:
dcade_cut =pd.cut(years,decade_bins)

In [127]:
dcade_cut


[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1980, 1990], (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000]]
Length: 11
Categories (6, interval[int64]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [129]:
dcade_cut.categories

IntervalIndex([(1960, 1970], (1970, 1980], (1980, 1990], (1990, 2000], (2000, 2010], (2010, 2020]],
              closed='right',
              dtype='interval[int64]')

In [132]:
pd.value_counts(dcade_cut)

(2010, 2020]    3
(1990, 2000]    3
(2000, 2010]    2
(1980, 1990]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

In [133]:
dcade_cut.hist()

AttributeError: 'Categorical' object has no attribute 'hist'

In [137]:
years.hist(alpha=0.5, bins=30);
# df.hist(alpha=0.5, bins=30);

AttributeError: 'list' object has no attribute 'hist'

In [138]:
np.random.seed(12345)

In [139]:
dfr =DataFrame(np.random.randn(1000,4))

In [158]:
a

A         1         2         3
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
..        ...       ...       ...       ...
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]

In [156]:
a =dfr.rename(columns={0:"A"})
# df.rename(columns={'A': 'a'}

In [157]:
dfr.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528