In [1]:
import numpy as np
5/2

2.5

In [4]:
array1 =np.array([[1,2,3,4],[8,9,10,11]])

In [5]:
array1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [6]:
array1*array1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [7]:
#それぞれの要素の掛け算がおこなれる


In [8]:
1/array1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [9]:
array1**4


array([[    1,    16,    81,   256],
       [ 4096,  6561, 10000, 14641]])

In [10]:
##ここまでが、lessom8

In [11]:
import numpy as np

In [14]:
arr =np.arange(1,11)

In [16]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr[8]

9

In [19]:
arr[1:5]

array([2, 3, 4, 5])

In [20]:
arr[0:5] =1100


In [21]:
arr

array([1100, 1100, 1100, 1100, 1100,    6,    7,    8,    9,   10])

In [24]:
arr =np.arange(1,11)
slice_arr =arr[0:6]  
slice_arr[:] = 99


In [25]:
slice_arr[:] 


array([99, 99, 99, 99, 99, 99])

In [26]:
arr


array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [27]:
# 参照のものであるため元のものも変更されるその時はコピーを使用する

In [28]:
arr_copy =arr.copy()

In [29]:
arr


array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [30]:
arr_copy


array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [31]:
arr_copy[:] =90


In [32]:
arr_copy


array([90, 90, 90, 90, 90, 90, 90, 90, 90, 90])

In [33]:
arr


array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [34]:
arr2nd=np.array([[1,2,3],[5,6,7],[10,11,15]])

In [35]:
arr2nd


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [10, 11, 15]])

In [36]:
arr2nd[0,1]

2

In [37]:
arr2nd[2,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [38]:
arr2nd[2,2]

15

In [39]:
arr2nd[:2,1:]

array([[2, 3],
       [6, 7]])

In [40]:
#2行目までと1個以降

In [41]:
arr2nd= np.zeros((10,10))

In [42]:
arr2nd


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
arr_length =arr2nd.shape[1]

In [45]:
arr2nd
for i in range(arr_length):
    arr2nd[i]=i

In [46]:
arr_length


10

In [47]:
arr2nd

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])