In [3]:
import numpy as np

In [5]:
arr = np.arange(9).reshape((3,3))

In [6]:
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr.T


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [8]:
np.dot(arr.T,arr)

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [9]:
#天地行列の掛け算のもの

In [10]:
#ここまでlesson10


In [11]:
import numpy as np
arr =np.array(11)


In [12]:
arr


array(11)

In [13]:
arr =np.arange(11)


In [14]:
aprr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
A=np.random.randn(10)

In [18]:
A

array([ 0.65435525, -0.24019345,  0.85223652,  0.0969639 , -2.14658136,
       -0.55250496, -0.43867811,  1.26538032, -0.44318526, -0.01870923])

In [19]:
A

array([ 0.65435525, -0.24019345,  0.85223652,  0.0969639 , -2.14658136,
       -0.55250496, -0.43867811,  1.26538032, -0.44318526, -0.01870923])

In [20]:
A=np.random.randn(10)


In [21]:
A



array([ 0.17185782, -0.54638492, -0.16583466, -0.79123074,  0.18913735,
        0.02305394,  0.06435973, -0.02054113, -0.66577222,  1.41663388])

In [23]:
B =np.random.randn(10)

In [24]:
B


array([ 0.7756266 ,  0.80952605,  0.09146146, -1.33782245,  0.8884812 ,
        0.86898787,  1.87464184, -0.006859  , -0.1107625 ,  0.39105626])

In [25]:
np.add(A,B)

array([ 0.94748442,  0.26314112, -0.07437319, -2.12905319,  1.07761855,
        0.89204181,  1.93900157, -0.02740014, -0.77653472,  1.80769014])

In [26]:
np.maximum(A,B)

array([ 0.7756266 ,  0.80952605,  0.09146146, -0.79123074,  0.8884812 ,
        0.86898787,  1.87464184, -0.006859  , -0.1107625 ,  1.41663388])